# Use Node.js v16 Alpine as the base image
FROM node:16-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy package.json (and possibly package-lock.json) to the container
COPY package.json ./

# Install dependencies in the container
RUN npm install

# Change the ownership of the /app directory to the 'node' user
# Alpine's node image includes a 'node' user by default, which you can use
RUN chown -R node:node /app

# Switch to 'node' user before copying source files and running the app
# This step ensures that the app runs with non-root privileges
USER node

# Copy the rest of the application code
COPY --chown=node:node . .


# Command to run the application
CMD ["npm", "run", "start"]
